// Code generated by 'yaegi extract github.com/aaydin-tr/divisor/middleware'. DO NOT EDIT.
package middleware

import (
	"reflect"

	"github.com/aaydin-tr/divisor/middleware"
)

var Symbols = map[string]map[string]reflect.Value{
	"github.com/aaydin-tr/divisor/middleware/middleware": {
		// function, constant and variable definitions
		"NewContext": reflect.ValueOf(middleware.NewContext),

		// type definitions
		"Context":    reflect.ValueOf((*middleware.Context)(nil)),
		"Middleware": reflect.ValueOf((*middleware.Middleware)(nil)),
		"New":        reflect.ValueOf((*middleware.New)(nil)),

		// interface wrapper definitions
		"_Middleware": reflect.ValueOf((*_github_com_aaydin_tr_divisor_middleware_Middleware)(nil)),
	},
}

// _github_com_aaydin_tr_divisor_middleware_Middleware is an interface wrapper for Middleware type
type _github_com_aaydin_tr_divisor_middleware_Middleware struct {
	IValue      interface{}
	WOnRequest  func(ctx *middleware.Context) error
	WOnResponse func(ctx *middleware.Context)
}

func (W _github_com_aaydin_tr_divisor_middleware_Middleware) OnRequest(ctx *middleware.Context) error {
	return W.WOnRequest(ctx)
}
func (W _github_com_aaydin_tr_divisor_middleware_Middleware) OnResponse(ctx *middleware.Context) {
	W.WOnResponse(ctx)
}
