type: round-robin # Load balancing algorithm; e.g round-robin, w-round-robin, ip-hash and random. Default: round-robin
port: 8000 # Server port.
host: localhost # Server host. Default: localhost
health_checker_time: 30s # Time interval to perform health check for backends. Default: 30 seconds
backends:
  - url: localhost:8080 # Backend url, do not present protocol
    health_check_path: /health # Health check path for backends. Default: /
    weight: 2 # Only mandatory for w-round-robin algorithm
    max_conn: 512 # Maximum number of connections which may be established to host listed in Addr. Default: 512
    max_conn_timeout: 30s # Maximum duration for waiting for a free connection. Default: 30 seconds
    max_conn_duration: 10s # Keep-alive connections are closed after this duration. Default: 10 seconds
    max_idle_conn_duration: 10s # Idle keep-alive connections are closed after this duration. Default: 10 seconds
    max_idemponent_call_attempts: 5 # Maximum number of attempts for idempotent calls. Default: 5
monitoring:
  port: 8001 # Monitoring server port , Default: 8001
  host: localhost # Monitoring server host, Default: localhost
custom_headers: # Custom headers will be set on request sent to backend; e.g $remote_addr, $time, $incremental, $uuid, Header name can be whatever you want as long as it's a string
  x-client-ip: $remote_addr # Client remote addr
  x-req-time: $time # Request time
  x-incremental-id: $incremental # Request incremental id for per backend
  x-uuid: $uuid # Request uuid 
server:
  http_version: http1 # Http version for frontend server, http1 and http2 is supported (http1 mean HTTP/1.1). Default: http1
  cert_file: "" # TLS cert file. Default: empty
  key_file: "" # TLS key file. Default: empty
  max_idle_worker_duration: 10s # MaxIdleWorkerDuration is the maximum idle time of a single worker in the underlying worker pool of the Server. Idle workers beyond this time will be cleared. Default: 10 seconds
  tcp_keepalive_period: 0s # Period between tcp keep-alive messages. TCP keep-alive period is determined by operation system by default. Default: 0
  concurrency: 262144 # The maximum number of concurrent connections the server may serve. Default: 262144
  read_timeout: 0s # ReadTimeout is the amount of time allowed to read the full request including body. Default: unlimited
  write_timeout: 0s # WriteTimeout is the maximum duration before timing out writes of the response. Default: unlimited
  idle_timeout: 0s # IdleTimeout is the maximum amount of time to wait for the next request when keep-alive is enabled. Default: unlimited
  disable_keepalive: false # The server will close all the incoming connections after sending the first response to client if this option is set to true. Default: false
  disable_header_names_normalizing: false # Header names are passed as-is without normalization if this option is set true. Default: false